<#include "/layout/head.ftl">
<#include "/layout/navigation.ftl">
<div class="container">
	<div class="row-fluid">
		<div id="homepage-intro" class="hero-unit">
			<h1>Take your Business Cards online!</h1>
			<p>Manage your Business cards, annotate, make collections, browse public ones.</p>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span8">
			<section id="homepage-activity">
				<header><h2>Recent public cards</h2></header>
				<#if (recentPublicCards?size > 0)>
					<#list recentPublicCards as card>
						<div class="card row-fluid">
							<div class="span6">
								<div class="card-image">
									<img src="/cardImage/${card.img.getKeyString()}" />
								</div>
								<div class="card-meta">
									<p>By ${card.owner} at ${card.created?date}</p>
								</div>
							</div>
							<div class="span6">
								<h4 class="card-name"><a href="/browse/card/${card.key.id?c}">${card.name!}</a></h4>
								<dl class="card-tags">
									<#list card.tags as tag>
										<dt>${tag.tagKey}</dt><dd>${tag.content}</dd>
									</#list>
								</dl>
							</div>
						</div>
					</#list>
				<#else>
					<p class="alert alert-danger">No cards</p>
				</#if>
			</section>
		</div>

		<div class="span4">
			<section id="homepage-features">
				<header><h2>About project</h2></header>
				<p class="well">Project was created as final project for <em>PA165 Enterprise Applications in Java at Faculty of Informatics, Masaryk University</em> and is completely open-source and free to reuse.</a></p>
				<h4>Google App Engine</h4>
				<p>Hosted at <a href="https://developers.google.com/appengine/">Google App Engine</a> - dynamic web server with full support for common web technologies, persistent storage, scaling, load-balancing, API for authenticating and much more.</p>
				<h4 class="margined">App Engine Datastore</h4>
				<p>Schemaless object datastore providing robust, scalable storage for your web application, with no planned downtime, atomic transactions, high availability of reads and writes, strong consistency for reads and ancestor queries, and eventual consistency for all other queries.</p>
				<h4 class="margined">Spring</h4>
				<p>Spring is the most popular application development framework for enterprise Java™. Millions of developers use Spring to create high performing, easily testable, reusable code without any lock-in.</p>
				<h4 class="margined">FreeMarker</h4>
				<p>FreeMarker is a "template engine"; a generic tool to generate text output (anything from HTML to autogenerated source code) based on templates. It's a Java package, a class library for Java programmers.</p>
				<h4 class="margined">Twitter Bootstrap</h4>
				<p>Simple and flexible HTML, CSS, and Javascript for popular user interface components and interactions.</p>
				<h4 class="margined">GitHub</h4>
				<p>Online project hosting using Git - free and open source distributed version control system. Includes source-code browser, in-line editing, wikis, and ticketing. Free for public open-source code.</p>
				<h4 class="margined">Eclipse, NetBeans, IntelliJ IDEA</h4>
				<p>Developed in free (community) versions of these IDEs.</p>
			</section>
		</div>
	</div>
</div>
<#include "/layout/debug.ftl">
<#include "/layout/footer.ftl">
<#include "/layout/foot.ftl">